### ISSUE TITLE
No text editor ? 

### ISSUE THREAD

**Issue by yakhyadabo** [confluentinc/cp-docker-images#833]
Is it a deliberate choice to not have any editor available ?
```
$ vi
/bin/sh: 37: vi: not found
$ pico
/bin/sh: 38: pico: not found
$ nano
/bin/sh: 39: nano: not found
$ ed
/bin/sh: 40: ed: not found
$ 
```
What's the proper way to edit a file, for a debugging purpose ?

**Comment by cricket007** [comment]
What files do you want to edit?

You can cat or more files to inspect contents

**Comment by ewencp** [comment]
In general, yes, this is intentional. Most people using docker images prefer to keep them as thin as possible for production. Some systems take this to an extreme, e.g. it's not uncommon to see go-based software deployed in an absolutely minimal Alpine image with just the binary added. 

You have a couple of options:

* Layer on top of these images with your own that extend them with whatever other contents you want. This can all be done via your build system.
* If this is more of a one-off thing, simply install whatever editor (and other tools) you like. You will need to `apt-get update` first because (for similar reasons) the package database is removed from the base image, but then just do something like `apt-get install nano` or whatever editor you want. This is a good option if you're not planning to use this regularly and are just trying to determine, e.g., why the arguments you're passing in aren't behaving as expected.
